package:
    name: pivy
    version: "master"

build:
    number: 0
    script_env:
        - USE_QT6=1  # [py >= 312]
        - USE_QT6=0  # [py < 312]

source:
  path: ../../

requirements:
    build:
        - compilers
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - msinttypes  # [win]
        - cmake
        - ninja
        - swig
    host:
        - python
        - coin3d
        - soqt      # [py < 312]
        - qt-main   # [py < 312]
        - soqt6     # [py >= 312]
        - qt6-main  # [py >= 312]
    run:
        - python
        - coin3d
        - qt-main   # [py < 312]
        - soqt      # [py < 312]
        - pyside2   # [py < 312]
        - qt6-main  # [py >= 312]
        - soqt6     # [py >= 312]
        - pyside6   # [py >= 312]

test:
    source-files:
        - tests/*
    imports:
        - pivy.coin
        - pivy.gui.soqt
    script:
        - coin_tests.py


about:
    home: https://github.com/FreeCAD/pivy
    license: ISC
    license_file: LICENSE
    summary: python bindings to coin3d.
    doc_url: https://github.com/FreeCAD/pivy
    dev_url: https://github.com/FreeCAD/pivy

extra:
    recipe-maintainers:
        - looooo
