package:
  name: pivy
  version: "master"

build:
  number: 0

source:
  path: ../../

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - msinttypes  # [win]
        - cmake
        - ninja
        - swig
    host:
        - python
        - coin3d
        - soqt
        - qt
    run:
        - python
        - coin3d
        - qt
        - pyside2
        - soqt

test:
    imports:
        - pivy.coin
        - pivy.gui.soqt

about:
    home: https://github.com/FreeCAD/pivy
    license: ISC
    license_file: LICENSE
    summary: python bindings to coin3d.
    doc_url: https://github.com/FreeCAD/pivy
    dev_url: https://github.com/FreeCAD/pivy

extra:
    recipe-maintainers:
        - looooo
