name: Build with vcpkg

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  buildme:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            vcpkg_triplet: x64-linux-release
          - os: macos-latest
            vcpkg_triplet: x64-osx-release
          - os: windows-latest
            vcpkg_triplet: x64-windows-release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu only)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config

      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          manifest-dir: ${{ github.workspace }}
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true

      - name: Configure CMake
        run: |
          cmake -S . -B build ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}

      - name: Build project
        run: |
          cmake --build build --config Release